### PR TITLE
Changes specific to Appdynamics.

### PR DESCRIPTION
**Pull request by pkumar-appd**

### CODE REVIEW

**Comment by jgawor** [comment]
Thanks for your contribution! However, we can't merge your stuff in unless you sign the individual or corporate CLA as indicated by the @cfdreddbot.

**Comment by nkatre** [comment]
Hi @jgawor the CLA is now signed and submitted to the CF org. Copying @chipchilders for confirmation.

Copying @akankshudhawan

**Comment by chipchilders** [comment]
@jgawor the CLA has been received. Feel free to merge!

**Comment by nkatre** [comment]
Hi @jgawor, can we merge this PR if there are no roadblocks ?

**Comment by degrim** [comment]
I see a couple of issues here.  
1) There is no documentation provided on how to configure and use this framework and there are no tests for the framework.
2) Line 200 of lib/liberty_buildpack/framework/appdynamics_agent.rb uses a hard-coded version number in the filename being extracted, this will fail if the user overrides the version number in the config using either an environment variable or by forking the buildpack and modifying the yml file.
3) Line 171 of lib/liberty_buildpack/framework/appdynamics_agent.rb contains a comment which talks about downloading a New Relic jar file?
4) Line 175 of lib/liberty_buildpack/framework/appdynamics_agent.rb will output an error message like `The app-dynamics.jar  app-dynamics-3.8.4.zip  format could not be matched from ...`.  This doesn't make sense to mention an app-dynamics.jar file file when there is an error downloading the .zip file specified in the uri.
5) Line 115 of lib/liberty_buildpack/framework/appdynamics_agent.rb, what is the significance of an agent with a length >= 40?
6) Copyright dates in config/appdynamicsagent.yml and lib/liberty_buildpack/framework/appdynamics_agent.rb are dated from 2014/2015 instead of 2016?

**Comment by pkumar-appd** [comment]
@jgawor I have updated the code as par the changes asked by @degrim . Can we get this PR merged.

**Comment by jgawor** [comment]
Thanks a lot for your contribution! I will go ahead and merge this PR but we might have some follow up changes. Also, we would love to have some tests.

**Pull request merged**
