### PR TITLE
JRebel improvements

### PR DESCRIPTION
**Pull request by dmitri-gb**
Changes:
- Add support for packaged servers and server directories
- Add support for EAR apps

I also had to change some code in `liberty.rb` in order to expand WAR archives that are inside EAR archives deployed to packaged servers or server directories. Previously, the way it worked was that the EARs were expanded during the compile phase, where as the WARs inside them were expanded in the release phase (because only then was `Dir.glob` able to find them). This also caused `Liberty.apps` to return different results during the two phases.

### CODE REVIEW

**Comment by dmitri-gb** [comment]
I believe you should already have my CLA.

**Comment by jgawor** [comment]
Thanks! Two comments:
-  Why the change the liberty.rb?
- In jrebel_agent.rb it might be easier just to search for `#{@app_dir}/**/WEB-INF/classes/rebel-remote.xml"`. Yes, that might find some apps that have this file but not actually be a war file. But I doubt we will have a lot of such cases. Besides, packaged servers or server directories usually contain the application files in the `apps` directory and not the `dropins` directory.

**Comment by dmitri-gb** [comment]
The change in `liberty.rb` was needed in order to expand WAR archives that are inside EAR archives. Previously the EARs were expanded in the compile phase, and then the WARs in the release phase. This, however, prevented us from finding `rebel-remote.xml` files (which we need to do in the compile phase).

I will simplify my changes to just search for `#{@app_dir}/**/WEB-INF/classes/rebel-remote.xml` like you suggested.

**Comment by jgawor** [comment]
Ok. In that case something like this should work also (and be a little simpler):
```ruby
 server_path = File.dirname(server_xml)
 ears = Dir.glob("#{server_path}/**/*.ear")
 Liberty.expand_apps(ears)
 wars = Dir.glob("#{server_path}/**/*.war")      
 Liberty.expand_apps(wars)
 apps_found = ears + wars
```

**Comment by dmitri-gb** [comment]
I was just unsure whether `Liberty.apps` should also return the **WARs that are inside EARs** or not. Previously, it _did not_ return them in the compile phase, where as it _did_ return them in the release phase.

Seeing as in the case where the user deploys a standalone EAR app (i.e. not a server directory / packaged server) the WARs inside are *never* returned, then I figured it makes sense to not return them here either.

The question is simply which is the correct behaviour? My code chooses to never return WARs, where as your code always does.

(To be clear, the JRebel integration only cares about what is expanded, not about what is returned from `Liberty.apps`.)

**Comment by jgawor** [comment]
The results of `Liberty.apps` are not really used anywhere except in a couple of tests. This function is primarily used for expanding the ear & war files and the way it is currently written it would return different results depending on when it was called. So, for now, go ahead with the change I suggested and we'll clean it up better later.

**Comment by mjear** [comment]
The whitelist has been updated to include dmitri-gb.  You can accept their pull request.

**Comment by jgawor** [comment]
Great. @dmitri-gb can you squash your commits?

**Comment by dmitri-gb** [comment]
Done.

**Comment by jgawor** [comment]
Awesome. Thanks!

**Pull request merged**
